<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '7a7203377ce5aa9b1970d0cbfac47954',
  'DATABASE_URL' => 'mysql://root@127.0.0.1:3306/tt?serverVersion=8&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'TWILIO_DSN' => 'twilio://9ZGKG5G7XHQP31N34SAG437Qfrom=+17206084561',
  'MAILER_DSN' => 'null://null',
);
